# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: /posts/:title
paginate: 10 # the number of post per page
rdiscount:
  extensions: [smart]

# User Options
name: Schoolies
baseurl:   '/schoolies'
description: 'A Jekyll theme for university writings, essays and beautiful photography.'
email: 
twitter: mektball
icon_url: 
disqus_shortname: 

# Color Options
text_color: '#444444'
accent_color: '#d95e3f'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#385975'
header_text_color: '#dfe6ec'
header_accent_color: '#ffffff'
header_title_color: '#ffffff'
header_subtle_color: '#597790'
header_subtle_border: '#597790'
background: '#fcfcfc'
post_background:

# Footer
footer_title: Katie B Ball
footer_description: 
social_links_title: 
github_url: roachhd
flickr_url: roachhd
instagram_url: RoachHD
vimeo_url: 
facebook_url: roachhd
google_plus_url: 
pinterest_url: 
tumblr_url: 
linkedin_url: 
dribbble_url: 
lastfm_url: 
rdio_url: 
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 
